language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libkyotocabinet-dev
install: gem build kyotocabinet.gemspec && gem install kyotocabinet-*.gem
script: ./test.rb
