language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1
before_install:
  - wget http://fallabs.com/kyotocabinet/pkg/kyotocabinet-1.2.76.tar.gz
  - tar -xzf kyotocabinet-1.2.76.tar.gz
  - cd kyotocabinet-1.2.76
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
install: gem build kyotocabinet.gemspec && gem install kyotocabinet-*.gem
script: ./test.rb
